apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/pittar/spring-petclinic.git'
        - name: revision
          value: master
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: maven
      params:
        - name: GOALS
          value:
            - package
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
  workspaces:
    - name: source
    - name: maven-settings
