apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-app-
spec:
  pipelineRef:
    name: build-app
  taskRunTemplate:
    podTemplate:
      env:
        - name: MAVEN_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_HOST  
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - configMap:
        name: maven-settings-cm
      name: maven-settings
    - name: quay-credentials
      secret:
        secretName: pittar-devsecops-pull-secret