apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: argocd
spec:
  extraConfig:
    accounts.rhdh: apiKey, login
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  server:
    insecure: true
    route:
      enabled: true
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  rbac:
    defaultPolicy: role:readonly
    policy: |
      g, openshift-gitops-admins, role:admin
      g, system:cluster-admins, role:admin
    scopes: "[groups]"