apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: 'https://quay.io'
  name: quay-creds
  namespace: petclinic-cicd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjR2wwZEdGeUsyUmxkbk5sWTI5d2N6b3lOMU0xV0VGUFZrdElVVVpSTmt4R1drMUROVGRWUjBwTVZUSllPREJIUXpOS01VVXlOREE1TkVZeVNEbGFOMWhMU2tGT1ExTktXVTlJVURKSVJFeEYiLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
