apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: 'https://quay.io'
  name: quay-creds
  namespace: petclinic-cicd
type: kubernetes.io/basic-auth
stringData:
  username: pittar+devsecops
  password: 27S5XAOVKHQFQ6LFZMC57UGJLU2X80GC3J1E24094F2H9Z7XKJANCSJYOHP2HDLE