apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
  name: gitea-create-pr
spec:
  params:
    - description: PR Title
      name: title
      type: string
    - default: ''
      description: The body of the PR request
      name: body
      type: string
    - default: ''
      description: password for tea cli
      name: password
      type: string
    - default: ''
      description: Gitea username
      name: username
      type: string
    - default: ''
      description: Gitea Email
      name: email
      type: string
    - default: ''
      description: Gitea server instance
      name: giteasrv
      type: string
    - default: ''
      description: Repository owner
      name: owner
      type: string
    - default: ''
      description: Repository name
      name: reponame
      type: string
    - default: ''
      description: Gitea branch to pr to
      name: gitref
      type: string
    - default: ''
      description: Gitea branch to pr from
      name: tagref
      type: string
  steps:
    - env:
        - name: GITHUB_USER
          value: $(params.username)
        - name: GITHUB_EMAIL
          value: $(params.email)
      image: 'quay.io/redhatworkshops/gitea-cli:latest'
      name: run-tea-cli
      resources: {}
      script: >
        #!/usr/bin/env bash

        curl -s --header "Content-Type: application/json" -u
        "$(params.username)":"$(params.password)" --request POST -d "{\"title\":
        \"$(params.title)\", \"head\": \"$(params.tagref)\",
        \"base\":\"$(params.gitref)\", \"body\": \"$(params.body)\"}"
        "$(params.giteasrv)"/api/v1/repos/$(params.owner)/$(params.reponame)/pulls
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source