apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
  name: kustomize
spec:
  params:
    - description: The placeholder image in the deployment to be replaced.
      name: image-name
      type: string
    - description: The image to update the deployment with.
      name: new-image-name
      type: string
    - description: The image to tag update the deployment with.
      name: new-tag
      type: string
    - description: Path to the overlay directory.
      name: overlaypath
      type: string
  steps:
    - image: 'quay.io/redhatworkshops/kustomize-task:v4.0.5'
      name: kustomize
      resources: {}
      script: >
        #!/usr/bin/env /bin/sh

        echo "Kustomizing image"

        echo "Running: kustomize edit set image
        $(params.image-name)=$(params.new-image-name):$(params.new-tag)"

        cd $(params.overlaypath)

        kustomize edit set image
        $(params.image-name)=$(params.new-image-name):$(params.new-tag)


        echo "Updated file kustomization.yaml file"

        cat kustomization.yaml
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source