apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  annotations:
    tekton.dev/git-0: http://gitea.scm.svc.cluster.local:3000
    tekton.dev/git-1: 'https://gitea-scm.apps.cluster-sqjrc.sqjrc.sandbox739.opentlc.com'
type: kubernetes.io/basic-auth
stringData:
  username: developer
  password: openshift