apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: pipeline
secrets:
  - name: gitea-creds
  - name: quay-creds
imagePullSecrets:
  - name: quay-creds
